import localFont from "next/font/local";
import "./globals.css";

const spectralBold = localFont({
  src: "./fonts/Spectral-Bold.ttf",
  variable: "--font-spectral-bold",
  weight: "100 900",
});
const spectralRegular = localFont({
  src: "./fonts/Spectral-Regular.ttf",
  variable: "--font-spectral-regular",
  weight: "100 900",
});

export const metadata = {
  title: "Spawn Cats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spectralBold.variable} ${spectralRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
